// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MythicNights.DataContext;

namespace MythicNights.Migrations
{
    [DbContext(typeof(MythicNightContext))]
    [Migration("20210809204155_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("MythicNights.DataContext.GuildConfig", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("MythicNights.DataContext.MythicNight", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attending")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MythicNights");
                });

            modelBuilder.Entity("MythicNights.DataContext.Player", b =>
                {
                    b.Property<ulong>("DiscordUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.HasKey("DiscordUserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MythicNights.DataContext.Toon", b =>
                {
                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsPrefered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Offspec")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("PlayerDiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferedRole")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RaiderIO")
                        .HasColumnType("REAL");

                    b.Property<string>("Realm")
                        .HasColumnType("TEXT");

                    b.Property<double>("iLvl")
                        .HasColumnType("REAL");

                    b.HasKey("FullName");

                    b.HasIndex("PlayerDiscordUserId");

                    b.ToTable("Toons");
                });

            modelBuilder.Entity("MythicNights.DataContext.Toon", b =>
                {
                    b.HasOne("MythicNights.DataContext.Player", null)
                        .WithMany("Toons")
                        .HasForeignKey("PlayerDiscordUserId");
                });

            modelBuilder.Entity("MythicNights.DataContext.Player", b =>
                {
                    b.Navigation("Toons");
                });
#pragma warning restore 612, 618
        }
    }
}
